[package]
name = "lasterm-hub-lock"
version = "0.6.0"
edition = "2021"
license = "AGPL-3.0-only"
repository = "https://github.com/khiops/lasterm"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi4"] }
napi-derive = "3"
lasterm-process-lock = { path = "../lasterm-process-lock" }

[build-dependencies]
napi-build = "2"
